### ISSUE TITLE
Swagger.json using HTTP instead of HTTPS

### ISSUE THREAD

**Issue by marceloodiniz** [Azure/azure-functions-openapi-extension#92]
As explained on issue #77 , when I access Swagger UI using HTTPS, it tries to access swagger.json using HTTP, which is disabled on Azure Function App. 

The version v0.6.0-preview did not resolve this problem.

**Comment by justinyoo** [comment]
Could you please let me know how to reproduce your issue on my end?

**Comment by justinyoo** [comment]
I published this [sample app](https://github.com/Azure/azure-functions-openapi-extension/tree/main/samples/Microsoft.Azure.WebJobs.Extensions.OpenApi.FunctionApp.V3Static), but I had no issue at all on my end.

https://fncapp-openapi-test-kc.azurewebsites.net/swagger/ui

**Comment by justinyoo** [comment]
I've got the same setting as yours mentioned in #77 - HTTPS only, minimum TLS version of 1.2.

Although I tried to access to the function app through HTTP, it's automatically redirected to HTTPS. It can't render anything through HTTP like your screenshot.

It would be really great to let me know your step-by-step repro process so that I can follow it and confirm the same issue occurs on my end.

**Comment by justinyoo** [comment]
@marceloodiniz Because I don't see any issue on my end and haven't got response from you with detailed step-by-step repro, I'll close this issue now.

If you still want to discuss, please provide us with the repro steps with details. Otherwise, we won't be able to sort this out.

**Comment by marceloodiniz** [comment]
It is not resolved @justinyoo .. 

You have to give me more time to do what you ask for me!!! I will open this issue many times !!!

**Comment by justinyoo** [comment]
@marcelaldecoa 

What I want you to give me is how you got your error. Your issue described in here and #77 won't be happening and doesn't make sense to me.

If you access to your Swagger UI through HTTPS, the doc also MUST go through HTTPS. if you go to your Swagger UI through HTTP, the doc also MUST go through HTTP, because the code is designed like that. There's no way that UI goes through HTTPS and doc goes through HTTP separately, unless you modified this package on your end.

I'll keep this issue close until you come up with the repro process.

**Comment by mirecad** [comment]
I have exactly the same problem. I managed to create a workaround by specifying server url in `IOpenApiConfigurationOptions`:

```
    public class OpenApiConfigurationOptions : IOpenApiConfigurationOptions
    {
        ...
        public List<OpenApiServer> Servers { get; set; } = new List<OpenApiServer>()
        {
            new OpenApiServer()
            {
                Url = "https://myhttpsurl.azurewebsites.net/api/"
            }
        };
        ...
    }
```
